# Generated by Django 3.2.16 on 2023-11-15 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='author_follower',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='follower',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subsriber', to='users.user', verbose_name='Subscriber'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('author', 'subscriber'), name='author_subscriber'),
        ),
    ]
